import images from './images';

const products = [
  {
    id: 1,
    name: 'Product 1',
    price: 100,
    brand: 'samsung',
    model: 'xpto',
    dimensions: '43.3 x 44.4 x 9.8t',
    image: images.watch1,
    description: 'Lorem ipsum dolor sit amet,',
    weight: '33.5g',
    wifi: 'Yes',
    bluetooth: 'Yes',
    resolution: '450x450',
  },
  {
    id: 2,
    name: 'Product 2',
    price: 200,
    brand: 'apple',
    model: 'iphone',
    dimensions: '43.3 x 44.4 x 9.8t',
    image: images.watch2,
    description: 'Lorem ipsum dolor sit amet,',
    weight: '33.5g',
    wifi: 'Yes',
    bluetooth: 'Yes',
    resolution: '450x450',
  },
  {
    id: 3,
    name: 'Product 3',
    price: 300,
    brand: 'apple',
    model: 'iphone',
    dimensions: '43.3 x 44.4 x 9.8t',
    image: images.watch3,
    description: 'Lorem ipsum dolor sit amet,',
    weight: '33.5g',
    wifi: 'Yes',
    bluetooth: 'Yes',
    resolution: '450x450',
  },
  {
    id: 4,
    name: 'Product 4',
    price: 400,
    brand: 'apple',
    model: 'iphone',
    dimensions: '43.3 x 44.4 x 9.8t',
    image: images.watch4,
    description: 'Lorem ipsum dolor sit amet,',
    weight: '33.5g',
    wifi: 'Yes',
    bluetooth: 'Yes',
    resolution: '450x450',
  },
  {
    id: 5,
    name: 'Product 5',
    price: 500,
    brand: 'apple',
    model: 'iphone',
    dimensions: '43.3 x 44.4 x 9.8t',
    image: images.watch5,
    description: 'Lorem ipsum dolor sit amet,',
    weight: '33.5g',
    wifi: 'Yes',
    bluetooth: 'Yes',
    resolution: '450x450',
  },
  {
    id: 6,
    name: 'Product 6',
    price: 600,
    brand: 'apple',
    model: 'iphone',
    dimensions: '43.3 x 44.4 x 9.8t',
    image: images.watch6,
    description: 'Lorem ipsum dolor sit amet,',
    weight: '33.5g',
    wifi: 'Yes',
    bluetooth: 'Yes',
    resolution: '450x450',
  },
  {
    id: 7,
    name: 'Product 7',
    price: 700,
    brand: 'apple',
    model: 'iphone',
    dimensions: '43.3 x 44.4 x 9.8t',
    image: images.watch7,
    description: 'Lorem ipsum dolor sit amet,',
    weight: '33.5g',
    wifi: 'Yes',
    bluetooth: 'Yes',
    resolution: '450x450',
  },
  {
    id: 8,
    name: 'Product 8',
    price: 800,
    brand: 'apple',
    model: 'iphone',
    dimensions: '43.3 x 44.4 x 9.8t',
    image: images.watch8,
    description: 'Lorem ipsum dolor sit amet,',
    weight: '33.5g',
    wifi: 'Yes',
    bluetooth: 'Yes',
    resolution: '450x450',
  },
  {
    id: 9,
    name: 'Product 9',
    price: 900,
    brand: 'apple',
    model: 'iphone',
    dimensions: '43.3 x 44.4 x 9.8t',
    image: images.watch9,
    description: 'Lorem ipsum dolor sit amet,',
    weight: '33.5g',
    wifi: 'Yes',
    bluetooth: 'Yes',
    resolution: '450x450',
  },
];

export default products;
